djangoProjecthotelllll/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('iniciohotell/', include('hotelhe.urls', namespace='iniciohotell'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelhe/urls.py
from django.urls import path
from . import views

app_name = "inicio"

urlpatterns = [
    path("inicio", views.list, name="list_inicio"),
    path('habitacionescrear', views.habitaciones, name="crear_habitaciones"),
    path('turismocrear', views.turismo, name="crear_turismoo"),
    path('mirarturismo', views.list_turismo, name="list_turismo"),
]

hotelhe/models.py
from django.db import models

# Create your models here.

class Turismo(models.Model):
    imagen = models.FileField(upload_to="")
    nombre = models.CharField(max_length=100)
    hora = models.CharField(max_length=100)
    precio = models.PositiveIntegerField()
    descripcion = models.CharField(max_length=300)

    class Meta:
        db_table = "turismo"


class Habitacion(models.Model):
    nombrePersona = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10)
    numeroPersonas = models.IntegerField()
    tipo = models.CharField(max_length=300)
    dias = models.IntegerField()

    class Meta:
        db_table = "habitaciones"

hotelhe/views.py
from django.shortcuts import render, redirect
from hotelhe.models import Habitacion, Turismo
# Create your views here.

def list(request):
    return render(request, "inicio/index.html")

def list(request):
    return render(request, "inicio/index.html")

def list_habitaciones(request):
    habitaciones = Habitacion.objects.all()
    return render(request, "inicio/habitaciones.html", {"habitaciones" : habitaciones})


def list_turismo(request):
    turismo = Turismo.objects.all()
    return render(request, "inicio/turismolist.html", {"turismo": turismo})


def habitaciones(request):
    if request.method == "GET":
        return render(request,"inicio/habitaciones.html")

    nombrePersona = request.POST["nombrepersona_habitaciones"]
    telefono = request.POST["telefono_habitaciones"]
    numeroPersonas = request.POST["npersonas_habitaciones"]
    tipo = request.POST["tipo_habitaciones"]
    dias = request.POST["dias_habitaciones"]

    guardar_habitaciones = Habitacion(nombrePersona=nombrePersona, telefono=telefono, numeroPersonas=numeroPersonas, tipo=tipo, dias=dias)
    guardar_habitaciones.save()

    return redirect('inicio:list_inicio')

def turismo(request):
    if request.method == "GET":
        return render(request,"inicio/turismocrear.html")
    imagen = request.FILES["imagen_turismo"]
    nombre = request.POST["nombre_turismo"]
    hora = request.POST["hora_turismo"]
    precio = request.POST["precio_turismo"]
    descripcion = request.POST["descripcion_turismo"]


    guardar_turismo = Turismo(imagen=imagen, nombre=nombre, hora=hora, precio=precio ,descripcion=descripcion)
    guardar_turismo.save()

    return redirect('inicio:list_turismo')

hotelhe/templates/inicio/habitaciones.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>La Herradura - Reservacion</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
</head>
<body class="bod">


<header id="header"  >
    <!-- Navegation Menu -->
    <nav class="menu">
        <div class="logobox" >
            <h1 class="logo"><a href="#">
                <i class="fas fa-horse"></i>
                La Herradura
            </a></h1>

            <span ><i class="fas fa-bars"></i></span>
        </div>

        <div class="list-container" >
             <ul class="lists">
               <li><a href="{% url 'inicio:list_inicio' %}" class="active">Inicio</a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Acerca de nosotros </a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Habitaciones</a></li>
                <li><a href="{% url 'inicio:crear_habitaciones'%}">Reservaciones</a></li>
                <li><a href="{% url 'inicio:list_turismo' %}">Turismo</a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Contacto</a></li>
            </ul>
        </div>
        </div>
    </nav>

</header>

<br><br><br><br><br><br>
      <figure class="img-header">
        <section class="form-register">

            <form action="{% url 'inicio:crear_habitaciones' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h4>Reservacion</h4>
            <input class="controls" type="text" name="nombrepersona_habitaciones" id="cantidad" placeholder="Ingrese su nombre">
            <input class="controls" type="text" name="telefono_habitaciones" id="telefono" placeholder="Telefono">
            <input class="controls" type="number" name="npersonas_habitaciones" id="cantidad" placeholder="Numero de Personas">
            <input class="controls" type="text" name="tipo_habitaciones" id="habitacion" placeholder="Tipo de Habitacion">
            <input class="controls" type="number" name="dias_habitaciones" id="dias" placeholder="Dias de alojamiento">
            <p>Estoy de acuerdo con <a href="#">Terminos y Condiciones</a></p>
            <button type="submit"> Enviar Reservacion </button>
            <p><a href="#">¿Ya reservo?</a></p>

            </form>
        </section>
    </figure>

</body>
</html>

hotelhe/templates/inicio/turismocrear.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>turismo</title>

    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">

</head>
<body class="bod">

<header id="header"  >
    <!-- Navegation Menu -->
    <nav class="menu">
        <div class="logobox" >
            <h1 class="logo"><a href="#">
                <i class="fas fa-horse"></i>
                La Herradura
            </a></h1>

            <span class="btn-menu"><i class="fas fa-bars"></i></span>
        </div>

        <div class="list-container" >
            <ul class="lists">
                <li><a href="{% url 'inicio:list_inicio' %}" class="active">Inicio</a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Acerca de nosotros </a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Habitaciones</a></li>
                <li><a href="{% url 'inicio:crear_habitaciones'%}">Reservaciones</a></li>
                <li><a href="{% url 'inicio:list_turismo' %}">Turismo</a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Contacto</a></li>
            </ul>
        </div>

    </nav>

</header>

<br><br><br><br><br><br>
        <section class="form-register">


             <form action="{% url 'inicio:crear_turismoo' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <input class="controls" type="file" name="imagen_turismo" id="habitacion" placeholder="Imagen">
            <input class="controls" type="text" name="nombre_turismo" id="cantidad" placeholder="Nombre ">
            <input class="controls" type="text" name="hora_turismo" id="hora" placeholder="Hora" >
            <input class="controls" type="number" name="precio_turismo" id="precio" placeholder="Precio ">
            <input class="controls" type="text" name="descripcion_turismo" id="description" placeholder="Descripcion ">

            <button type="submit"> Agregar Producto </button>
             </form>

        </section>

</body>
</html>

hotelhe/templates/inicio/turismolist.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>La Herradura - turismo</title>
     <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
</head>
<body >

<header id="header"  >
    <!-- Navegation Menu -->
    <nav class="menu">
        <div class="logobox" >
            <h1 class="logo"><a href="#">
                <i class="fas fa-horse"></i>
                La Herradura
            </a></h1>

            <span class="btn-menu"><i class="fas fa-bars"></i></span>
        </div>

        <div class="list-container" >
            <ul class="lists">
                <li><a href="{% url 'inicio:list_inicio' %}" class="active">Inicio</a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Acerca de nosotros </a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Habitaciones</a></li>
                <li><a href="{% url 'inicio:crear_habitaciones'%}">Reservaciones</a></li>
                <li><a href="{% url 'inicio:list_turismo' %}">Turismo</a></li>
                <li><a href="{% url 'inicio:list_inicio' %}">Contacto</a></li>
            </ul>
        </div>
    </nav>

</header>



</body>
</html>